pybo/views/fanswer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import FanswerForm
from pybo.models import Free, Fanswer
from pybo.views.auth_views import login_required

bp = Blueprint('fanswer', __name__, url_prefix='/fanswer')


@bp.route('/create/<int:free_id>', methods=('POST',))
@login_required
def create(free_id):
    form = FanswerForm()
    free = Free.query.get_or_404(free_id)
    if form.validate_on_submit():
        content = request.form['content']
        fanswer = Fanswer(content=content, create_date=datetime.now(), user=g.user)
        free.fanswer_set.append(fanswer)
        db.session.commit()
        return redirect('{}#fanswer_{}'.format(
            url_for('free.detail', free_id=free_id), fanswer.id))
    return render_template('free/free_detail.html', free=free, form=form)


@bp.route('/modify/<int:fanswer_id>', methods=('GET', 'POST'))
@login_required
def modify(fanswer_id):
    fanswer = Fanswer.query.get_or_404(fanswer_id)
    if g.user != fanswer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('free.detail', free_id=fanswer.free.id))
    if request.method == "POST":
        form = FanswerForm()
        if form.validate_on_submit():
            form.populate_obj(fanswer)
            fanswer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect('{}#fanswer_{}'.format(
                url_for('free.detail', free_id=fanswer.free.id), fanswer.id))
    else:
        form = FanswerForm(obj=fanswer)
    return render_template('fanswer/fanswer_form.html', form=form)


@bp.route('/delete/<int:fanswer_id>')
@login_required
def delete(fanswer_id):
    fanswer = Fanswer.query.get_or_404(fanswer_id)
    free_id = fanswer.free.id
    if g.user != fanswer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(fanswer)
        db.session.commit()
    return redirect(url_for('free.detail',free_id=free_id))


@bp.route('/vote/<int:fanswer_id>/')
@login_required
def vote(fanswer_id):
    fanswer = Fanswer.query.get_or_404(fanswer_id)
    if g.user == fanswer.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        fanswer.voter.append(g.user)
        db.session.commit()
    return redirect('{}#fanswer_{}'.format(
                url_for('free.detail', free_id=fanswer.free.id), fanswer.id))

pybo/views/free_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import FreeForm, FanswerForm
from pybo.models import Free, Fanswer, User
from pybo.views.auth_views import login_required

bp = Blueprint('free', __name__, url_prefix='/free')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    free_list = Free.query.order_by(Free.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Fanswer.free_id, Fanswer.content, User.username) \
            .join(User, Fanswer.user_id == User.id).subquery()
        free_list = free_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.free_id == Free.id) \
            .filter(Free.subject.ilike(search) |  # 질문 제목
                    Free.content.ilike(search) |  # 질문 내용
                    User.username.ilike(search) |  # 질문 작성자
                    sub_query.c.content.ilike(search) |  # 답변 내용
                    sub_query.c.username.ilike(search)  # 답변 작성자
                    ) \
            .distinct()
    free_list = free_list.paginate(page, per_page=10)
    return render_template('free/free_list.html', free_list=free_list, page=page, kw=kw)


@bp.route('/detail/<int:free_id>/')
def detail(free_id):
    form = FanswerForm()
    free = Free.query.get_or_404(free_id)
    return render_template('free/free_detail.html', free=free, form=form)


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = FreeForm()
    if request.method == 'POST' and form.validate_on_submit():
        free = Free(subject=form.subject.data, content=form.content.data,
                            create_date=datetime.now(), user=g.user)
        db.session.add(free)
        db.session.commit()
        return redirect(url_for('free._list'))
    return render_template('free/free_form.html', form=form)


@bp.route('/modify/<int:free_id>', methods=('GET', 'POST'))
@login_required
def modify(free_id):
    free = Free.query.get_or_404(free_id)
    if g.user != free.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('free.detail', free_id=free_id))
    if request.method == 'POST':  # POST 요청
        form = FreeForm()
        if form.validate_on_submit():
            form.populate_obj(free)
            free.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('free.detail', free_id=free_id))
    else:  # GET 요청
        form = FreeForm(obj=free)
    return render_template('free/free_form.html', form=form)


@bp.route('/delete/<int:free_id>')
@login_required
def delete(free_id):
    free = Free.query.get_or_404(free_id)
    if g.user != free.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('free.detail', free_id=free_id))
    db.session.delete(free)
    db.session.commit()
    return redirect(url_for('free._list'))


@bp.route('/vote/<int:free_id>/')
@login_required
def vote(free_id):
    free = Free.query.get_or_404(free_id)
    if g.user == free.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        free.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('free.detail', free_id=free_id))

pybo/templates/free/free_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
      <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <h2 class="border-bottom py-2">{{ free.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ free.content|markdown }}</div>
            <div class="d-flex justify-content-end">
                {% if free.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ free.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ free.user.username }}</div>
                    <div>{{ free.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{{ url_for('free.vote', free_id=free.id) }}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ free.voter|length }}</span>
                </a>
            {% if g.user == free.user %}
            <a href="{{ url_for('free.modify', free_id=free.id) }}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{{ url_for('free.delete', free_id=free.id) }}">삭제</a>
            {% endif %}
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ free.fanswer_set|length }}개의 댓글이 있습니다.</h5>
    {% for fanswer in free.fanswer_set %}
    <a id="fanswer_{{ fanswer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"><strong>{{ fanswer.user.username }}</strong>
                {{ fanswer.content|markdown }}</div>
            <!--<<div class="d-flex justify-content-end">
                {% if fanswer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ fanswer.modify_date|datetime }}</div>
                </div>
                {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ fanswer.user.username }}</div>
                    <div>{{ fanswer.create_date|datetime }}</div>
                </div>
            </div>-->
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{{ url_for('fanswer.vote', fanswer_id=fanswer.id) }}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ fanswer.voter|length }}</span>
                </a>
            {% if g.user == fanswer.user %}
            <a href="{{ url_for('fanswer.modify', fanswer_id=fanswer.id) }}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{{ url_for('fanswer.delete', fanswer_id=fanswer.id) }}">삭제</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('fanswer.create', free_id=free.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content">댓글 내용</label>
            <textarea {% if not g.user %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="1"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/free/free_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <!--
        <label class="form-label" for="customFile">첨부 파일 선택</label>
        <input type="file" class="form-control" id="customFile" />
        <br>첨부파일  -->
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/free/free_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">

    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if free_list %}
        {% for free in free_list.items %}
        <tr class="text-center">
            <td>{{ free_list.total - ((free_list.page-1) * free_list.per_page) - loop.index0 }}</td>
            <td class="text-start">
                <a href="{{ url_for('free.detail', free_id=free.id) }}">{{ free.subject }}</a>
                {% if free.fanswer_set|length > 0 %}
                <span class="text-danger small mx-2">{{ free.fanswer_set|length }}</span>
                {% endif %}
            </td>
            <td>{{ free.user.username }}</td>
            <td>{{ free.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if free_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ free_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in free_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != free_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if free_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ free_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <div class="row my-3">
        <div class="col-6">
            <a href="{{ url_for('free.create') }}" class="btn btn-primary">게시글 작성하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="searchForm" method="get" action="{{ url_for('free._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}