pybo/views/about_views.py
from flask import Blueprint, render_template

bp = Blueprint('about', __name__, url_prefix='/about')
#About
@bp.route('/intro/')
def intro():
    return render_template('about/intro.html')

@bp.route('/gamerule/')
def gamerule():
    return render_template('about/gamerule.html')

pybo/views/auth_views.py
import functools

from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm, MyPageForm
from pybo.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        user_email = User.query.filter_by(email=form.email.data).first()
        user_phone = User.query.filter_by(phone=form.phone.data).first()
        if not user: #사용자 이름 중복이 없다면
            if not user_email: #이메일 중복이 없다면
                if not user_phone: #휴대폰 중복이 없다면
                    user = User(username=form.username.data,
                                password=generate_password_hash(form.password1.data),
                                email=form.email.data,
                                phone = form.phone.data,
                                birth = form.birth.data)
                    db.session.add(user)
                    db.session.commit()
                    return redirect(url_for('main.index'))
                else:
                    flash('이미 존재하는 전화번호입니다.')
            else:
                flash('이미 존재하는 이메일입니다.')
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

@bp.route('/mypage/', methods=('GET', 'POST'))
@login_required
def mypage():
    form = MyPageForm()
    user_id = session.get('user_id')
    if request.method == 'POST' and form.validate_on_submit(): #버튼 눌리면
        g.user = User.query.get(user_id)  #user_id를 통해 정보 불러옴
        if g.user.username is not form.username or g.user.phone is not form.phone:
            # 이름이나 전화번호에 수정이 있다면
            g.user.username = form.username.data #변경
            g.user.phone = form.phone.data #변경
            db.session.commit() #커밋
            return redirect(url_for('main.index')) #메인화면으로 이동
    return render_template('auth/mypage.html', form=form)

pybo/views/team_views.py
from flask import Blueprint, render_template

bp = Blueprint('team', __name__, url_prefix='/team')
#team
@bp.route('/woori/')
def woori():
    return render_template('team/woori.html')

@bp.route('/samsung/')
def samsung():
    return render_template('team/samsung.html')

@bp.route('/hana/')
def hana():
    return render_template('team/hana.html')

@bp.route('/bnk/')
def bnk():
    return render_template('team/bnk.html')

@bp.route('/kb/')
def kb():
    return render_template('team/kb.html')

@bp.route('/shinhan/')
def shinhan():
    return render_template('team/shinhan.html')

pybo/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

pybo/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/navbar.html
<!-- 네비게이션바 -->
<!-- 배경 색 bg-light border-bottom-->
<nav class="navbar navbar-expand-lg navbar-light"
     style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">WKBL</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownWKBL" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    WKBL
                  </a>
                  <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownWKBL">
                    <li><a class="dropdown-item" href="{{ url_for('about.intro') }}">소개</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('about.gamerule') }}">경기 규칙</a></li>
                    <!--<li><a class="dropdown-item" href="#">농구 용어</a></li>-->
                  </ul>
                </li>
              </ul>
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('news._list') }}">NEWS</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownTeam" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    TEAM
                  </a>
                  <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownTeam">
                    <li><a class="dropdown-item" href="{{ url_for('team.woori') }}">우리은행</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('team.samsung') }}">삼성생명</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('team.shinhan') }}">신한은행</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('team.hana') }}">하나원큐</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('team.bnk') }}">BNK 썸</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('team.kb') }}">KB스타즈</a></li>
                  </ul>
                </li>
              </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownBoard" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    BOARD
                  </a>
                  <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownBoard">
                    <li><a class="dropdown-item" href="{{ url_for('question._list')}}">Q&A</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('free._list')}}">자유게시판</a></li>
                  </ul>
                </li>
              </ul>

        </div>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- 오른쪽으로 아예 정렬 하고 싶다면 justify-content-end 사용 -->
            {% if g.user %}
            <ul class="navbar-nav">

                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }}(로그아웃)</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.mypage') }}">마이페이지</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>

            </ul>
            {% endif %}
        </div>
    </div>
</nav>