pybo/views/news_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import NewsForm
from pybo.models import News,User
from pybo.views.auth_views import login_required

bp = Blueprint('news', __name__, url_prefix='/news')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    news_list = News.query.order_by(News.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        #sub_query = db.session.query(News.id, News.content, User.username) \
            #.join(User,News.id == User.id).subquery()

        news_list = news_list \
            .join(User) \
            .filter(News.subject.ilike(search) |  # 뉴스제목
                    News.content.ilike(search) |  # 뉴스내용
                    User.username.ilike(search)   # 뉴스작성자
                    ) \
            .distinct()
    news_list = news_list.paginate(page, per_page=10)
    return render_template('news/news_list.html', news_list=news_list, page=page, kw=kw)



@bp.route('/detail/<int:news_id>/')
def detail(news_id):
    news = News.query.get_or_404(news_id)
    return render_template('news/news_detail.html', news=news)

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = NewsForm()
    if request.method == 'POST' and form.validate_on_submit():
        news = News(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(news)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('news/news_form.html', form=form)

@bp.route('/modify/<int:news_id>', methods=('GET', 'POST'))
@login_required
def modify(news_id):
    news = News.query.get_or_404(news_id)
    if g.user != news.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('news.detail', news_id=news_id))
    if request.method == 'POST':  # POST 요청
        form = NewsForm()
        if form.validate_on_submit():
            form.populate_obj(news)
            news.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('news.detail', news_id=news_id))
    else:  # GET 요청
        form = NewsForm(obj=news)
    return render_template('news/news_form.html', form=form)

@bp.route('/vote/<int:news_id>/')
@login_required
def vote(news_id):
    news = News.query.get_or_404(news_id)
    if g.user == news.user:
        flash('본인이 작성한 글은 추천할수 없습니다')
    else:
        news.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('news.detail', news_id=news_id))

@bp.route('/delete/<int:news_id>')
@login_required
def delete(news_id):
    news = News.query.get_or_404(news_id)
    if g.user != news.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('news.detail', news_id=news_id))
    db.session.delete(news)
    db.session.commit()
    return redirect(url_for('news._list'))

pybo/templates/news/news_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
     <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 기사 -->
    <h2 class="border-bottom py-2">{{ news.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ news.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ news.user.username }}</div>
                    <div>{{ news.create_date|datetime }}</div>
                </div>
            </div>
        </div>
        <div class="my-3">
            <a href="javascript:void(0)" data-uri="{{ url_for('news.vote', news_id=news.id) }}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{ news.voter|length }}</span>
            </a>
            {% if g.user == news.user %}
            <a href="{{ url_for('news.modify', news_id=news.id) }}"
               class="btn btn-sm btn-outline-secondary">수정</a>
             <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{{ url_for('news.delete', news_id=news.id) }}">삭제</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/news/news_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">기사등록</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/news/news_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">

    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if news_list %}
        {% for news in news_list.items %}
        <tr class="text-center">
            <td>{{ news_list.total - ((news_list.page-1) * news_list.per_page) - loop.index0 }}</td>
            <td class="text-start">
                <a href="{{ url_for('news.detail', news_id=news.id) }}">{{ news.subject }}</a>
            </td>
            <td>{{ news.user.username }}</td>
            <td>{{ news.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">기사가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if news_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ news_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in news_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != news_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if news_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ news_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <div class="row my-3">
        <div class="col-6">
        <!--wkbl인 사람만 글 작성할 수 있도록 유도-->
        {% if g.user.username == "WKBL" %}
        <a href="{{ url_for('news.create') }}" class="btn btn-primary">기사 작성하기</a>
        {% endif %}
        </div>

        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>


</div>
<form id="searchForm" method="get" action="{{ url_for('news._list')}}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}